# Based off the C/C++ Template from GitHub
name: C/C++ CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
    - name: make check
      run: make check
#    - name: make distcheck
#      run: make distcheck
